### PR TITLE
fix: Use guard pattern to allow consumers to ensure final trace is sent

### LINKED ISSUE #184: init-tracing-opentelemetry: Regression on flushing all traces at program termination
I believe this to be a consequence of https://github.com/open-telemetry/opentelemetry-rust/issues/1961

Using these versions:
```toml
[dependencies]
init-tracing-opentelemetry = { version = "0.19", features = [
  "otlp",
  "tls",
  "tracing_subscriber_ext",
] }
opentelemetry = "0.23"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1.40"
```

This code works (I can get a trace):
```rust
#[tracing::instrument]
async fn hello() -> () {
    tracing::info!("Hello World!");
}

#[tokio::main]
async fn main() {
    match std::env::var("OTEL_SERVICE_NAME") {
        Ok(_) => (),
        Err(_) => std::env::set_var("OTEL_SERVICE_NAME", "hello"),
    };
    init_tracing_opentelemetry::tracing_subscriber_ext::init_subscribers().expect("Tracing setup");
    hello().await;
    opentelemetry::global::shutdown_tracer_provider();
}
```

But when I change to these versions, the trace doesn't get emitted:
```toml
[dependencies]
init-tracing-opentelemetry = { version = "0.24", features = [
  "otlp",
  "tls",
  "tracing_subscriber_ext",
] }
opentelemetry = "0.27"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1.40"
```

With this grossest of workarounds I can get the trace to show up again:
```diff
@@ -12,4 +12,5 @@ async fn main() {
     init_tracing_opentelemetry::tracing_subscriber_ext::init_subscribers().expect("Tracing setup");
     hello().await;
     opentelemetry::global::shutdown_tracer_provider();
+    std::thread::sleep(std::time::Duration::from_millis(8000));
 }

```

### PR DESCRIPTION
**Pull request by masongup-mdsol**
In discussion with the Rust OpenTelemetry crate maintainers, the `shutdown_tracer_provider` function intentionally no longer ensures that the final traces are sent to the OpenTelemetry server before the application exits. To perform this functionality, we now need to call `force_flush` on the TracerProvider instance.

Since the public API functions for the TracerProvider only return a trait object which does not have this function exposed, we need to keep an instance of the actual TracerProvider around. In order to make this simple for consumers of this crate, I have used the guard pattern here so that they do not need to worry about those details or pull in the crates that provide those types. An instance of the TracerProvider is kept in a private field of the TracingGuard struct, which is returned by the init functions. That struct impls `Drop` to call `force_flush` when the struct is dropped. As such, crate consumers only need to use the `let _guard =` syntax to ensure the guard is only dropped when the function actually exits. This also allows us to, in the future, include other provider flushes in the same pattern, such as for OpenTelemetry logs and metrics.

In addition, as the `Drop` impl only performs a `force_flush`, if any consumers of this crate update to a version with this and do not make any code changes, their code will continue to behave exactly the same - the guard struct will be dropped immediately, triggering the `force_flush`, but the provider will continue to operate. Their application will behave exactly as it did before with regard to sending traces. It only loses the behavior of ensuring the final traces are sent before application exit, but that wasn't working before this anyways.

Resolves #184

### CODE REVIEW

**Comment by nshalman** [comment]
This does work for me, but does require the expected code changes in the consuming code.
One option is to mark the existing function with `#[deprecated]` and provide a new function name that returns the guard.
However we proceed it would be great to get some form of this into the library.
Thank you @masongup-mdsol!

File: init-tracing-opentelemetry/src/tracing_subscriber_ext.rs [hunk 1]
```diff
@@ -88,22 +88,34 @@ where
...
+    tracerprovider: trace::TracerProvider,
+}
+
+impl Drop for TracingGuard {
+    fn drop(&mut self) {
+        self.tracerprovider.force_flush();
+    }
+}
+
+pub fn init_subscribers() -> Result<TracingGuard, Error> {
```
Comment (davidB) [inline init-tracing-opentelemetry/src/tracing_subscriber_ext.rs:105]: Suggestion annotate with `#[must_use]` to raise a warning when the output is not managed.

If it doesn't behave as expected, I'll deprecate the previous signature as suggested by @nshalman

**Review by davidB — CHANGES_REQUESTED** [review]
Thank you. I'll do a release after merge & validation.

File: init-tracing-opentelemetry/src/tracing_subscriber_ext.rs (hunk 1 above)
Comment (masongup-mdsol) [reply init-tracing-opentelemetry/src/tracing_subscriber_ext.rs:106]: I had to put the `#[must_use]` on the struct instead of the function, as on the function it acts on the `Result` instead of the `TracingGuard`.

It seems to behave well to me - it's a warning instead of an error, so existing code will still compile without any changes.

**Comment by masongup-mdsol** [comment]
I did the updates in all the places I could find, It's possible I missed some though.

**Comment by davidB** [comment]
Thank you. Did you have a compilation warning on examples without guard (after setting the `#[must_buse]`)?

**Comment by nshalman** [comment]
Thank you both!
